### ISSUE TITLE
Undefined "self" on js/column.js#L621

### ISSUE THREAD

**Issue by kkc-yuki** [olifolkerd/tabulator#2711]
**Describe the bug**
When I run the test in my app using tabulator module in node package,
the following error appeared.

```
     ReferenceError: self is not defined
      at Column._buildColumnHeaderContent (node_modules\tabulator-tables\dist\js\tabulator.js:1939:13)
      at Column._buildHeader (node_modules\tabulator-tables\dist\js\tabulator.js:1571:30)
      at new Column (node_modules\tabulator-tables\dist\js\tabulator.js:1410:8)
      at ColumnCalcs.initialize (node_modules\tabulator-tables\dist\js\tabulator.js:11639:20)
      at new ColumnCalcs (node_modules\tabulator-tables\dist\js\tabulator.js:11629:8)
      at Tabulator.bindModules (node_modules\tabulator-tables\dist\js\tabulator.js:10199:25)
      at Tabulator._create (node_modules\tabulator-tables\dist\js\tabulator.js:8109:8)
      at new Tabulator (node_modules\tabulator-tables\dist\js\tabulator.js:7417:8)
```

Then, I add the code `var self = this` in dist\js\tabulator..js:1939,
it works fine.

**Tabulator Info**
- 4.6.0

**Working Example**
I tried to simulate this problem with JSBin, but I could not.
But to show what my code looks like, I will put the link below.

https://jsbin.com/hinanetepo/edit?html,js,console,output

**To Reproduce**
1. Include tabulator with npm
2. Call Tabulator module with 'new Tabulator'
3. See the error.

**Expected behavior**
Can call tabulator module properly.

**Screenshots**
See the error message above.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - package system; NPM
 - environment: Powershell 

**Additional context**
I found that there is a undefined self on https://github.com/olifolkerd/tabulator/blob/master/src/js/column.js#L621 .
Maybe this cause the problem?

**Comment by olifolkerd** [comment]
Hey @kkc-yuki 

Thanks for the headsup,

I have pushed a fix for this to the matser branch and will include it in this weekends patch release.

Cheers

Oli :)
