### ISSUE TITLE
Tabulator 4.7.2 with IE11 second time `setData` throw error

### ISSUE THREAD

**Issue by kacchi** [olifolkerd/tabulator#2921]
**Describe the bug**
tabulator 4.7.2 degrade in the execution of 'setData' after the second time
with only IE11

**Tabulator Info**
- 4.7.2
(4.7.1, 4.7.0, 4.6.3, 4.6.2 does not happen)

**Working Example**
https://codepen.io/kacchi/pen/BaKBORM
(debug URL for IE11 https://cdpn.io/kacchi/debug/BaKBORM/GnMnbOxWagvM)
tabulator-tables 4.7.2
promise-polyfill 8.1.3(latest)

**To Reproduce**
1. Open codepen in IE11
2. See error
```
Possible Unhandled Promise Rejection: TypeError: Unable to get property 'add' of undefined or null reference
TypeError: Unable to get property 'add' of undefined or null reference
   at s.prototype.styleRow (https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/js/tabulator.min.js:3:23236)
   at s.prototype._virtualRenderFill (https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/js/tabulator.min.js:3:23981)
   at s.prototype.reRenderInPosition (https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/js/tabulator.min.js:3:20717)
   at s.prototype.redraw (https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/js/tabulator.min.js:3:30611)
   at s.prototype.adjustTableSize (https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/js/tabulator.min.js:3:29791)
   at s.prototype._wipeElements (https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/js/tabulator.min.js:3:8864)
   at s.prototype._setDataActual (https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/js/tabulator.min.js:3:7861)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/tabulator/4.7.2/js/tabulator.min.js:3:7734)
    :
```
**Expected behavior**
display "bar"

**Screenshots**
![image](https://user-images.githubusercontent.com/530187/89384995-edbe4980-d739-11ea-8702-48fac8d3259f.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Internet Explorer
 - Version 11
(chrome, Edge work fine)

**Comment by olifolkerd** [comment]
I am unable to replicate your error in my IE browser. 

The only thing i can think is that you are calling setData twice in a row, which may break as you are not waiting from the promise of the first function to return before executing the second, which means that you could be trying to set data while the table is still updating from the first call.

Cheers

Oli :)

**Comment by kacchi** [comment]
Thanks and I apologize...
We try to start a fix our code or contribute to vue-tabulator.
