### ISSUE TITLE
TypeError: Cannot set property 'paddingTop' of undefined in Tabulator Versions > 4.7.2

### ISSUE THREAD

**Issue by MickeWest** [olifolkerd/tabulator#3006]
**Describe the bug**
Hi -

I have encountered an unhandled exception since moving to version 4.8+ of Tabulator. I can pinpoint where the error is occurring but not why.
This occurs when trying to delete a column in the table and may be a race condition between the clearing of the vertical align and the column no longer existing?
For any version 4.7.2 and earlier this error does not manifest itself. See details below and the StackBlitz provided, Any help of tracking down what is causing this error would be much appreciated.

Below is my code snippets that is executed when the error occurs (the unhandled exception occurs when the ```
'columnToDelete.delete();' line is executed):

```
let columnToDelete;

// Delete the Column Identified by the Item ID
columnToDelete = this.table.columnManager.columns.find((column: Tabulator.ColumnComponent) => column.definition.field === itemId);

if (columnToDelete) {
	columnToDelete.delete();
}

```
`Below is the actual cause of the unhandled exception in file tabulator.es2015.js. The line 'this.element.style.paddingTop = "";' is causing the exception due to that 'style' is undefined at this point.
//clear vertical alignmenet
```
Column.prototype.clearVerticalAlign = function () {
	this.element.style.paddingTop = "";
	this.element.style.height = "";
	this.element.style.minHeight = "";
	this.groupElement.style.minHeight = "";

	this.columns.forEach(function (column) {
		column.clearVerticalAlign();
	});
};

```

Below is the print of the Unhandled Exception and the stack trace:

```
Unhandled Promise rejection: Cannot set property 'paddingTop' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot set property 'paddingTop' of undefined
    at Column.push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.Column.clearVerticalAlign (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2143:1)
    at c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2149:1
    at Array.forEach (<anonymous>)
    at Column.push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.Column.clearVerticalAlign (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2148:1)
    at c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:665:1
    at Array.forEach (<anonymous>)
    at ColumnManager.push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.ColumnManager._verticalAlignHeaders (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:661:1)
    at ColumnManager.push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.ColumnManager.deregisterColumn (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:1184:1)
    at c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2468:1
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:11463:29) {stack: 'TypeError: Cannot set property 'paddingTop' o…(http://localhost:4200/polyfills.js:11463:29)', message: 'Cannot set property 'paddingTop' of undefined'} TypeError: Cannot set property 'paddingTop' of undefined
    at Column.push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.Column.clearVerticalAlign (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2143:1)
    at c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2149:1
    at Array.forEach (<anonymous>)
    at Column.push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.Column.clearVerticalAlign (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2148:1)
    at c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:665:1
    at Array.forEach (<anonymous>)
    at ColumnManager.push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.ColumnManager._verticalAlignHeaders (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:661:1)
    at ColumnManager.push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.ColumnManager.deregisterColumn (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:1184:1)
    at c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2468:1
    at new ZoneAwarePromise (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:876:1)


push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.Column.clearVerticalAlign (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2143)
<anonymous> (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:665)
push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.ColumnManager._verticalAlignHeaders (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:661)
push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.ColumnManager.deregisterColumn (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:1184)
<anonymous> (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2468)
ZoneAwarePromise (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:876)
push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.Column.delete (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2438)
<anonymous> (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2442)
<anonymous> (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2441)
ZoneAwarePromise (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:876)
push../node_modules/tabulator-tables/dist/js/tabulator.es2015.js.Column.delete (c:\Projects\BlackFishDashboard\front\node_modules\tabulator-tables\dist\js\tabulator.es2015.js:2438)
RemoveColumn (c:\Projects\BlackFishDashboard\front\src\app\kernel-tools\kernel-benchmarks-tool\kernel-benchmarks-tool.component.ts:1362)
<anonymous> (c:\Projects\BlackFishDashboard\front\src\app\kernel-tools\kernel-benchmarks-tool\kernel-benchmarks-tool.component.ts:1185)
<anonymous> (c:\Projects\BlackFishDashboard\front\node_modules\tslib\tslib.es6.js:74)
ZoneAwarePromise (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:876)
__awaiter (c:\Projects\BlackFishDashboard\front\node_modules\tslib\tslib.es6.js:70)
UpdateTableDataSource (localhost꞉4200/main.js:6006)
<anonymous> (c:\Projects\BlackFishDashboard\front\src\app\kernel-tools\kernel-benchmarks-tool\kernel-benchmarks-tool.component.ts:391)
fulfilled (c:\Projects\BlackFishDashboard\front\node_modules\tslib\tslib.es6.js:71)
invoke (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:359)
run (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:124)
<anonymous> (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:855)
invokeTask (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:391)
runTask (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:168)
drainMicroTaskQueue (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:559)
invokeTask (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:469)
invokeTask (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:1603)
globalZoneAwareCallback (c:\Projects\BlackFishDashboard\front\node_modules\zone.js\dist\zone-evergreen.js:1629)

```

**Tabulator Info**
- Any version above 4.7.2 has this Exception
- All versions <= 4.7.2 does not have this Exception

**Working Example**
Made a StackBlitz, hopefully this also be ok?
https://stackblitz.com/edit/angular-ivy-p2hwkh

**To Reproduce**
A step by step guide to recreate the issue in your JS Fiddle or Codepen:
1. Go to 'https://stackblitz.com/edit/angular-ivy-p2hwkh'
2. Click on the 3 buttons in order as named: 1., 2., 3.
3. Scroll down to console to see the Unhandled exception in file tabulator.es2015.js (See stack trace and Error message above).
4. See error that the 'style' Object of the line 'this.element.style.paddingTop' is undefined in function: 'Column.prototype.clearVerticalAlign'

**Expected behavior**
I expect the Tabulator Column Delete function to return without error or exception for all versions of Tabulator
The StackBlitz example clearly shows the erroneous behavior occurring, 

**Screenshots**
No Screenshots required for this error.

**Desktop (please complete the following information):**
 - OS: [Windows 10 and Linux 18.04]
 - Browser [chrome]
 - Version [Version 85.0.4183.83 (Official Build) (64-bit)]

**Additional context**

**Comment by olifolkerd** [comment]
Hey @MickeWest 

Thanks for getting in touch, looks like you have found a bug there

I will be honest, i had never anticipated people trying to add nested columns through the ***addColumn*** function. 

I will look at gettting a patch out for that in the next couple of weeks.

on a side not you don't need to call the redraw function after adding or deleting a column to the table. it will do this all by itself.  the redraw function is only ever needed if you have changed the dimensions of the table or you drew it when the table element was hidden, the issue you are experiencing is because i had never really intended the use of the ***addColumns*** function for adding nested columns so the table isn't property recursing through the children for layout

Cheers

Oli :)

**Comment by MickeWest** [comment]
Hi @olifolkerd

Thanks for the quick response and for the great Tabulator tool, which is very impressive for displaying data in tables.
A question on your comment above, if 'addColumn" was not intended to be used for nested columns, what should I use for this task? I read through the docs but did not find a suitable other function for this.

Thanks again!

    Michael

**Comment by olifolkerd** [comment]
Hey @MickeWest 

I have pushed a fix for this to the master branch and will include it in a patch release later today.

Cheers

Oli :)
