### ISSUE TITLE
Ajax: Set custom headers on tabulator setData

### ISSUE THREAD

**Issue by lzacha** [olifolkerd/tabulator#329]
Hello Oli,

I was trying to set customs headers to some ajax request and following the examples (http://olifolkerd.github.io/tabulator/docs/#set-data) , I cant solve it.

This examples works fine:
$("#example-table").tabulator("setData","http://www.getmydata.com/now");
$("#example-table").tabulator("setData","http://www.getmydata.com/now", {key1:"value1", key2:"value2"});
$("#example-table").tabulator("setData","http://www.getmydata.com/now", {}, "POST"); //make a post request

But this doesn't:
var ajaxConfig = {
    type:"POST", //set request type to Position
    contentType: 'application/json; charset=utf-8', //set specific content type
};

$("#example-table").tabulator("setData","http://www.getmydata.com/now", {}, ajaxConfig); //make ajax request with advanced config options

Based in this last one i try a simple example like this,

    var ajaxConfig = {
        contentType: 'application/json; charset=utf-8',
        headers: {
            'x-probot1':'123',
            'x-probot2':'456'
        }
    };

    $("#ajax-trigger").click(function(){
        $("#example-table").tabulator("setData", "https://api.test.com/sites/", {} ,ajaxConfig);
        // THIS WORKS --> $("#example-table").tabulator("setData", "https://api.test.com/sites/");
    });

I'm getting some jquery errors(i try with differents jquery version getting the same result):

Uncaught TypeError: s.type.toUpperCase is not a function
    at Function.ajax (https://code.jquery.com/jquery-3.2.1.js:9061:19)
    at t.(anonymous function).(anonymous function)._getAjaxData (https://cdnjs.cloudflare.com/ajax/libs/tabulator/2.11.0/tabulator.js:1509:5)
    at t.(anonymous function).(anonymous function)._getAjaxData (https://code.jquery.com/ui/1.12.1/jquery-ui.min.js:6:4499)
    at t.(anonymous function).(anonymous function).setData (https://cdnjs.cloudflare.com/ajax/libs/tabulator/2.11.0/tabulator.js:1470:11)
    at t.(anonymous function).(anonymous function).setData (https://code.jquery.com/ui/1.12.1/jquery-ui.min.js:6:4499)
    at HTMLDivElement.<anonymous> (https://code.jquery.com/ui/1.12.1/jquery-ui.min.js:6:5474)
    at Function.each (https://code.jquery.com/jquery-3.2.1.js:362:19)
    at jQuery.fn.init.each (https://code.jquery.com/jquery-3.2.1.js:157:17)
    at jQuery.fn.init.t.fn.(anonymous function) [as tabulator] (https://code.jquery.com/ui/1.12.1/jquery-ui.min.js:6:5357)
    at HTMLButtonElement.<anonymous> (http://localhost:8080/probot/newOrders:74:29)

Do you have a working example setting customs http headers?

Regards,

**Comment by olifolkerd** [comment]
Hey,

Thanks for getting in touch.

have you tried using the new 3.0 beta version yet, it has had a complete ajax systems overhaul and should be much more reliable,

http://olifolkerd.github.io/tabulator/examples/3.0/

Cheers

Oli

**Comment by olifolkerd** [comment]
Did version 3.0 workout for you?

**Comment by boctulus** [comment]
Hi!! This librart is amazing but I'm having the SAME problem with Tabulator 5.4 (custom headers are not passing to serverside)
