### ISSUE TITLE
addRow() throws exception with dataTree + bottomCalc

### ISSUE THREAD

**Issue by germanfr** [olifolkerd/tabulator#3578]
**Describe the bug**
When using the options `dataTree: true` + `dataTreeChildColumnCalcs: true` and you try to add a row to the table using `table.addRow(data, true)` it throws this error if a column has the **bottomCalc** option defined:

<details>
  <summary><b>Exception trace (expand)</b></summary>

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'open')
TypeError: Cannot read properties of undefined (reading 'open')
    at ColumnCalcs.js:339:1
    at Array.forEach (<anonymous>)
    at ColumnCalcs.rowsToData (ColumnCalcs.js:335:1)
    at ColumnCalcs.recalc (ColumnCalcs.js:242:1)
    at ColumnCalcs.recalcActiveRows (ColumnCalcs.js:103:1)
    at ColumnCalcs.rowsUpdated (ColumnCalcs.js:98:1)
    at InternalEventBus.js:119:1
    at Array.forEach (<anonymous>)
    at InternalEventBus._dispatch (InternalEventBus.js:118:1)
    at RowManager.dispatch (CoreFeature.js:78:1)
    at RowManager.addRow (RowManager.js:281:1)
    at RowManager.js:305:1
    at Array.forEach (<anonymous>)
    at RowManager.js:304:1
    at new ZoneAwarePromise (zone-evergreen.js:960:1)
    at RowManager.addRows (RowManager.js:291:1)
    at resolvePromise (zone-evergreen.js:798:1)
    at resolvePromise (zone-evergreen.js:750:1)
    at zone-evergreen.js:860:1
    at ZoneDelegate.invokeTask (zone-evergreen.js:399:1)
    at Object.onInvokeTask (core.js:28289:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398:1)
    at Zone.runTask (zone-evergreen.js:167:1)
    at drainMicroTaskQueue (zone-evergreen.js:569:1)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484:1)
    at invokeTask (zone-evergreen.js:1621:1)
    at XMLHttpRequest.globalZoneAwareCallback (zone-evergreen.js:1658:1)
```
</details>

**Tabulator Info**
5.1.0

**Working Example**
https://jsfiddle.net/L63ukx2q/5/

**To Reproduce**
1. Have a table with `dataTree: true` + `dataTreeChildColumnCalcs: true` and a column with bottomCalc.
2. Call `table.addRow(data)`.

**Expected behavior**
To not throw an error.

**Desktop**
Tested on:
* Chrome 97
* Firefox 96

**Additional context**
Browsing the source code I've found out that the reason of the exception is that `row.modules` is empty. The initialization code of the DataTree module runs on the `"row-init"` internal event, which is successfully called **after** the exception occurs.

I believe the solution would be to somehow ensure the initialization of the row is called **before** this line `if(row.modules.dataTree.open)` so that it is defined and it does not throw the exception.

<details>
  <summary><b>DataTree.js (expand)</b></summary>

```js
initializeRow(row){
	// ...

	row.modules.dataTree = {
		index: row.modules.dataTree ? row.modules.dataTree.index : 0,
		open: children ? (row.modules.dataTree ? row.modules.dataTree.open : this.startOpen(row.getComponent(), 0)) : false,
		controlEl: row.modules.dataTree && children ? row.modules.dataTree.controlEl : false,
		branchEl: row.modules.dataTree && children ? row.modules.dataTree.branchEl : false,
		parent: row.modules.dataTree ? row.modules.dataTree.parent : false,
		children:children,
	};
}
```

</details>

**Comment by olifolkerd** [comment]
Hey @germanfr 

I have pushed a fix for this to the master branch and will include it in this weekends patch release.

Cheers

Oli :)
