### ISSUE TITLE
Nested Tables: error on mouse hover

### ISSUE THREAD

**Issue by rodrigocl** [olifolkerd/tabulator#3807]
on Tooltip.js, line 51:
Uncaught TypeError: Cannot read properties of undefined (reading 'definition') Uncaught TypeError: Cannot read properties of undefined (reading 'definition')
    at Tooltip.mousemoveCheck (Tooltip.js:51:57)
    at InternalEventBus.js:119:42
    at Array.forEach (<anonymous>)
    at InternalEventBus._dispatch (InternalEventBus.js:118:21)
    at InteractionManager.dispatch (CoreFeature.js:78:10)
    at InteractionManager.triggerEvents (InteractionMonitor.js:303:10)
    at InteractionManager.track (InteractionMonitor.js:195:8)

it happens even if tooltip is set to false on columnDefault

**Comment by olifolkerd** [comment]
Hey @rodrigocl 

Without seeing how your table is setup and how the error actually gets triggered it is pretty much impossible to offer you a solution.

Please submit issues using the [Bug Report Template](https://github.com/olifolkerd/tabulator/issues/new?assignees=&labels=Possible+Bug&template=bug_report.md&title=) and provide a link to a JS Fiddle or Code Pen that demonstrates your setup.

Cheers

Oli :)
