### ISSUE TITLE
Issue with table.getHtml and table.download(html)

### ISSUE THREAD

**Issue by KlankSmash** [olifolkerd/tabulator#3817]
When using the table.getHtml() function I get this error in the console. I see the same error in the current example for Download Table Data on Tabulator.info

> Export.js:531 
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Export.js:531:8
    at Array.forEach (<anonymous>)
    at Export.genereateRowElement (Export.js:469:15)
    at Export.js:337:22
    at Array.forEach (<anonymous>)
    at Export.genereateTableElement (Export.js:322:8)
    at Export.genereateHTMLTable (Export.js:568:27)
    at TabulatorFull.html (html.js:3:39)
    at Download.download (Download.js:65:17)
    at table.<computed> [as download] (Module.js:38:16)

Link to a JSFiddle example of the issue.
[https://jsfiddle.net/stantond/gyn5foq3/4/](url)

**Comment by olifolkerd** [comment]
Hey @KlankSmash 

Thanks for the headsup, i have pushed a fix for this to the 5,3 branch and will include in the release in a couple of weeks.

Cheers

Oli :)
