### ISSUE TITLE
moving rows between groups gives error when history:true

### ISSUE THREAD

**Issue by scry-UrjitDesai** [olifolkerd/tabulator#4340]
When I try to move a row from one group to another even though it moves successfully I get an error in the console. 

This happens only when history is set to true. If I remove the history property, no error is printed in the console. 
Error- 
```
core.mjs:8400 ERROR TypeError: to.getPosition is not a function
    at History.rowMoved (tabulator_esm.js:12626:70)
    at tabulator_esm.js:24317:25
    at Array.forEach (<anonymous>)
    at InternalEventBus._dispatch (tabulator_esm.js:24316:21)
    at RowManager.dispatch (tabulator_esm.js:79:30)
    at RowManager.moveRow (tabulator_esm.js:22847:8)
    at MoveRows.endMove (tabulator_esm.js:14778:27)
    at ZoneDelegate.invokeTask (zone.js:434:35)
    at core.mjs:23896:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23896:36)
```
Version- 5.5.2
JS Fiddle- https://jsfiddle.net/v5k728gc/4/

**Comment by olifolkerd** [comment]
Duplicate of #3954
