### ISSUE TITLE
totWidth undefined

### ISSUE THREAD

**Issue by wp4nuv** [olifolkerd/tabulator#487]
Has anyone come across this issue when loading a table definition with percentage widths?
```
tabulator.min.js:1 Uncaught ReferenceError: totWidth is not defined
    at https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/js/tabulator.min.js:1:6797
    at Array.forEach (<anonymous>)
    at n.getFlexBaseWidth (https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/js/tabulator.min.js:1:6618)
    at L.update (https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/js/tabulator.min.js:5:2910)
    at n.fitToTable (https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/js/tabulator.min.js:1:5830)
    at n.redraw (https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/js/tabulator.min.js:1:7726)
    at n.setColumns (https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/js/tabulator.min.js:1:2456)
    at $.(anonymous function).(anonymous function)._buildElement (https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/js/tabulator.min.js:2:19548)
    at $.(anonymous function).(anonymous function)._buildElement (https://bln.dev/Members/js/jquery-ui.js?1500398571:415:25)
    at $.(anonymous function).(anonymous function)._create (https://cdnjs.cloudflare.com/ajax/libs/tabulator/3.2.0/js/tabulator.min.js:2:18606)
```
This is a copy of my init section
```
$("#table-bln-tabulator").tabulator({
            height: "400px",
            dateFormat: "mm/dd/yyyy",
            progressiveRender: true,
            index: "budget_id",
            fitColumns: true, //fit columns to width of table (optional)
            responsiveLayout: true,
            placeholder: "No Data Available",
            columns: [ //Define Table Columns
        { title: "Item", field: "rehab_item", width: "20%", editable:false },
        { title: "Description", field: "notes", editor:"textarea", editable: true, width: "50%", formatter:"html"},
        { title: "Quantity", field: "quantity", align:"right", editable: true, editor:"number", width: "12%",bottomCalc:fakeCalc },
        { title: "Amount",bottomCalc:totalCalc, field: "budget_amount", formatter: amount_format, editable: true, editor:amountEditor, width: "12%" },
        
        {
            title: "", editor: false, align:"center", width: 53, formatter: delete_button, headerSort: false, tooltip:"Delete", cellClick: function (e, cell) {
                console.log(cell.getData());
                var _data = cell.getData();
                var budget_id = _data.budget_id;
                var base = getBaseURL();
                var request_url = base + 'rehab_budget/delete_value';
                $.ajax({
                    url: request_url,
                    type: "POST",
                    data: { id: budget_id }
                }).done(function (data) {
                    var row = cell.getRow();
                    row.delete();
                    $("#table-bln-tabulator").tabulator("setData");
                });

            }
        },
            ],
            ajaxURL: request_url,
            ajaxResponse: function (url, params, response) {
                console.log(response);
                //save property id in hidden field
                $('#prop_id').val(response[0].client_property_id);
                if (response[0].budget_amount) {
                    $("#table-bln-tabulator").show();
                } else {
                    $("#table-bln-tabulator").hide();
                }
                return response;

            },
            cellEdited: function (cell) {
                var id = cell.getRow().getIndex();
                var data = cell.getData();
                var field = cell.getColumn().getField();
                data.property_rehab_item_id = data.rehab_item;
                var base = getBaseURL();
                var request_url = base + 'rehab_budget/update_value';
                $.ajax({
                    url: request_url,
                    type: "POST",
                    data: { dbid: id, dbfield: field, dbdata: data }
                }).done(function (data) {
                    cell.getElement().addClass("success");
                });
            }
        });
```

**Comment by olifolkerd** [comment]
Hey,

There was a bug causing the error, which i have just pushed a fix to the master branch for, i will include it in the patch release this afternoon.

On a separate note there are a few issues with your table definition that will be worth fixing.

There is no need to set the ***editable*** property to true, if you define an ***editor*** for the column it will be editable be default.

There is no point using ***fitColumns*** if you are going to define the width of all the columns. the whole point of fitColumns is that it will adjust the width of any columns without a defined width to take up all available space on the table.

If you are oing to use the ***responsive*** table mode you will want to define a ***minWidth*** on your columns so that Tabulator knows when to remove them

As of v3.0 the ***progressiveRender*** option is no longer available, it has been replaced with the virtual DOM which is enabled by default.

Thanks for the heads up on the bug.

Cheers

Oli
