### ISSUE TITLE
Sorting and Custom Sorting Issues

### ISSUE THREAD

**Issue by tomheaps** [olifolkerd/tabulator#606]
I have two columns next to each other:
```
{
        title: "Elapsed",
        field: "elapsed",
        formatter: timeElapsed,
        width: 120,
        align: "center",
        visible: false,
      }, {
        title: "LOS",
        field: "los",
        align: "center",
        width: 120,
        formatter: cLos,
        sorter: customSort, 
        sortable: true  
      }
```

I would like to be able to sort LOS (which contains humanized time values e.g. 1h 5min) by the data in the Elapsed column (which contains minutes as an integer e.g.  65). I have tried using the customSort function as you described in issue #166 i.e.

 ```
 var customSort = function(a, b, aData, bData) {
    return String(a.elapsed).localeCompare(String(b.elapsed));
  }
```

However this is producing bizarre results when clicking on header to sort - only one row seems to move up and down - not sure what I'm doing wrong here??

Other related issue is when you sort by a column that has empty cells in it, how can you stop those empty cells appearing at the top when dir = "asc"?

Many thanks for any help.

**Comment by olifolkerd** [comment]
Could you post a copy of your table constructor so i c an see how your sorter is applied.

Cheers

Oli

**Comment by tomheaps** [comment]
Hi,

I have tried putting the sorter function directly into the column definition as well:

```
{
        title: "LOS",
        field: "los",
        align: "center",
        width: 120,
        formatter: cLos,
        sorter: function(a, b, aData, bData) {
          return String(a.time).localeCompare(String(b.time));
        }
      }
```

But I still get the same buggy result with the sorter only moving a few rows back and forth (some of these rows have empty cells in the fields being sorted but this shouldn't cause a problem).

The code for my whole table is rather lengthy:

```
  var editCheck = function(cell) {
    var data = cell.getRow().getData();
    return data.name !== undefined
  }

  var customSort = function(a, b, aData, bData) {
    return String(a.time).localeCompare(String(b.time));
  }

  var specialtyEditor = function(cell, onRendered, success, cancel) {
    var editor = $("<select class='form-control'><option value=''></option><option value='Cardiology'>Cardiology</option><option value='Frailty'>Frailty</option><option value='Orthopaedics'>Orthopaedics</option><option value='Respiratory'>Respiratory</option><option value='Surgical'>Surgical</option></select>");
    editor.val(cell.getValue());
    onRendered(function() {
      editor.focus();
    });
    editor.on("change blur", function(e) {
      success(editor.val());
    });
    return editor;
  };

  var outcomeEditor = function(cell, onRendered, success, cancel) {
    var editor = $("<select class='form-control'><option value=''></option><option value='Potential Discharge'>? Discharge</option><option value='Definite Discharge'>Discharge</option><option value='AMU'>Stay on AMU</option><option value='Any Medical'>Any Medical</option><option value='Any CoE'>Any CoE</option><option value='Avon'>Avon</option><option value='Castle'>Castle</option><option value='CCU'>CCU</option><option value='Fairfax'>Fairfax</option><option value='Farries'>Farries</option><option value='ITU'>ITU</option><option value='Malins'>Malins</option><option value='Mary'>Mary</option><option value='Nicholas'>Nicholas</option><option value='Victoria'>Victoria</option></select>");
    editor.val(cell.getValue());
    onRendered(function() {
      editor.focus();
    });
    editor.on("change blur", function(e) {
      success(editor.val());
    });
    return editor;
  }

  var allocatedEditor = function(cell, onRendered, success, cancel) {
    var editor = $("<select class='form-control'><option value=''></option><option value='Avon'>Avon</option><option value='Castle'>Castle</option><option value='CCU'>CCU</option><option value='Fairfax'>Fairfax</option><option value='Farries'>Farries</option><option value='ITU'>ITU</option><option value='Malins'>Malins</option><option value='Mary'>Mary</option><option value='Nicholas'>Nicholas</option><option value='Victoria'>Victoria</option></select>");
    editor.val(cell.getValue());
    onRendered(function() {
      editor.focus();
    });
    editor.on("change blur", function(e) {
      success(editor.val());
    });
    return editor;
  }

  var doneNotdone = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    if (cellValue == "true") {
      return "<i class='green fal fa-check'></i>"
    } else if (cellValue == "false") {
      return "<i class='red fal fa-times'></i>"
    }
  };

  var checkBox = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    if (cellValue == "done") {
      return "<i class='green fa fa-check-circle'></i>"
    } else if (cellValue == "yes") {
      return "<i class='red fa fa-circle'></i>"
    } else if (cellValue === undefined) {
      return ""
    }
  };

  var checkBox2 = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    if (cellValue == "done") {
      return "<i class='green fa fa-check-circle'></i>"
    } else if (cellValue == "yes") {
      return "<i class='orange fa fa-circle'></i>"
    } else if (cellValue == "urgent") {
      return "<i class='red fa fa-circle'></i>"
    }
  };

  var thinkGlucose = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    if (cellValue == "true") {
      return '<span class="fa-layers" style="font-size:1rem"><i class="red fa fa-circle"></i><span class="fa-layers-text fa-inverse" data-fa-transform="shrink-5">D</span></span>'
    }
    if (cellValue == "false") {
      return ""
    }
  };

  var moveRow = function(cell, formatterParams) {
    return "<i class='blue fal fa-arrows-v'></i>"
  };

  var outcomeFormatter = function(cell, formatterParams) {
    var cellValue = cell.getValue();
    if (cellValue == "AMU") {
      return "<span style='color:#fa5252;font-family:Suisse-Black;'>" + cellValue + "</span>"
    } else if (cellValue == "Definite Discharge") {
      return "<i class='green fal fa-home'></i>"
    } else if (cellValue == "Potential Discharge") {
      return "<i class='orange fal fa-home'></i>"
    } else {
      return cellValue
    }
  };

  var timeElapsed = function(cell, formatterParams) {
    var timeCol = cell.getData().time;
    var startTime = moment(timeCol, "YY MM DD HH mm");
    var currentTime = moment();
    var elapsedTime = currentTime.diff(startTime, 'minutes');
    if (timeCol === undefined) {
      return undefined
    } else {
      return elapsedTime
    }
  }

  var cLos = function(cell, formatterParams) {
    var timeCol = cell.getData().time;
    var startTime = moment(timeCol, "YY MM DD HH mm");
    var currentTime = moment();
    var elapsedTime = currentTime.diff(startTime, 'minutes');
    var los = moment.duration(elapsedTime, "minutes").format("d[d] h[h] m[m]");
    if (timeCol === undefined) {
      return undefined
    } else if ((elapsedTime > 119) && (elapsedTime < 240)) {
      cell.getElement().css('color', '#fcc419');
      return los;
    } else if (elapsedTime > 239) {
      cell.getElement().css('color', '#fa5252');
      return los;
    } else {
      return los
    }
  }

  var deleteIcon = function(cell, formatterParams) {
    return "<i class='red fal fa-minus-circle'></i>";
  };

  var admitIcon = function(cell, formatterParams) {
    return "<i class='blue fal fa-plus-circle'></i>";
  };

  var moveIcon = function(cell, formatterParams) {
    return "<i class='blue fal fa-arrows-v'></i>";
  };

  function saveData() {
    var data = $("#amu-whiteboard").tabulator("getData");
    localStorage.setItem("tabulator-data", JSON.stringify(data));
  }

  function statusUpdate() {
    var emptyBeds = $('[tabulator-field="name"]:empty').length;
    var sr1 = $('.tabulator-row:nth-of-type(29) [tabulator-field="name"]:empty').length;
    var sr2 = $('.tabulator-row:nth-of-type(30) [tabulator-field="name"]:empty').length;
    var b1 = $('.tabulator-row:nth-of-type(7) [tabulator-field="name"]:empty').length;
    var b2 = $('.tabulator-row:nth-of-type(8) [tabulator-field="name"]:empty').length;
    var c10 = $('.tabulator-row:nth-of-type(27) [tabulator-field="name"]:empty').length;
    var c11 = $('.tabulator-row:nth-of-type(28) [tabulator-field="name"]:empty').length;
    var emptySR = sr1 + sr2 + b1 + b2 + c10 + c11;
    $('#emptyBeds').text(emptyBeds);
    $('#emptySR').text(emptySR);
    var avg = 0;
    var amount = 0;
    var elapsedData = $('[tabulator-field="elapsed"]:not(:empty)');
    elapsedData.each(function() {
      avg += +($(this).text());
      amount++;
    });
    avg /= amount;
    var avLOS = moment.duration(avg, "minutes").format("d[d] h[h] m[m]");
    $("#avLOS").text(avLOS);
    var defDisch = $('.green.fa-home').length;
    var potDisch = $('.orange.fa-home').length;
    var discharges = defDisch + potDisch;
    $('#discharges').text(discharges);
    $('#potDisch').text(potDisch);
  }

  function sortByBed() {
    $("#amu-whiteboard").tabulator("setSort", "bed", "asc");
  }

  function checkDuplicates() {
    var nameCells = $('#amu-whiteboard .tabulator-cell[tabulator-field="name"]'),
      htmlStrings = new Array(nameCells.length),
      i, j, current, comparing;
    for (i = 0; i < nameCells.length; i++) {
      current = htmlStrings[i];
      if (!current) {
        current = {
          html: nameCells.get(i).innerHTML,
          isDup: false
        };
        htmlStrings[i] = current;
      }
      if (current.isDup) {
        continue;
      }
      for (j = i + 1; j < nameCells.length; j++) {
        comparing = htmlStrings[j];
        if (!comparing) {
          comparing = {
            html: nameCells.get(j).innerHTML,
            isDup: false
          };
          htmlStrings[j] = comparing;
        }
        if (comparing.isDup) {
          continue;
        }
        if (current.html === comparing.html) {
          current.isDup = true;
          comparing.isDup = true;
          nameCells.eq(j).css('color', '#fa5252');
        }
      }
      if (current.isDup) {
        nameCells.eq(i).css('color', '#fa5252');
      }
    }
  }

  //Build Table-------------------------------------------------------------------

  $("#amu-whiteboard").tabulator({
    fitColumns: true,
    resizableColumns: false,
    history: true,
    index: "bed",
    initialSort: [{
      column: "bed",
      dir: "asc"
    }],
    ajaxLoaderLoading: "Updating Data",
    ajaxLoaderError: "Error Updating Data </br> Data will be lost if you log off!",
    columns: [{
        title: "Bed",
        field: "bed",
        align: "center",
        headerSort: false,
        width: 80,
        sorter: "alphanum"
      },
      {
        title: "Patient Name",
        field: "name",
        width: 300,
        sorter: "string",
        cellClick: function(e, cell) {
          if (cell.getValue() === undefined) {
            return false
          } else {
            var row = cell.getRow()
            var bed = row.getIndex();
            var name = cell.getValue();
            var fullName = name.split(', ');
            var lastName = fullName[0];
            var firstName = fullName[fullName.length - 1];
            $('#bedNo').text(bed);
            $('#forenameEdit').val(firstName);
            $('#surnameEdit').val(lastName);
            $('#editModal').modal('show');
          }
        }
      }, {
        title: "Time",
        field: "time",
        align: "center",
        sorter: "number",
        //editor: true,
        visible: false,
      }, {
        title: "Elapsed",
        field: "elapsed",
        formatter: timeElapsed,
        width: 120,
        align: "center",
        sorter: "number",
        visible: false,
      }, {
        title: "LOS",
        field: "los",
        align: "center",
        width: 120,
        formatter: cLos,
        sorter: customSort
      }, {
        title: "Specialty",
        field: "specialty",
        align: "center",
        width: 140,
        editable: editCheck,
        editor: specialtyEditor,
        formatter: function(cell, formatterParams) {
          var cellValue = cell.getValue();
          if (cellValue == "Surgical") {
            cell.getRow().getElement().css({
              "background-color": "rgba(250,82,82,0.2)"
            });
            return cellValue;
          } else if (cellValue == "Respiratory") {
            cell.getRow().getElement().css({
              "background-color": "rgba(255, 212, 59,0.2)"
            });
            return cellValue;
          } else if (cellValue == "Frailty") {
            cell.getRow().getElement().css({
              "background-color": "rgba(105, 219, 124,0.2)"
            });
            return cellValue;
          } else if (cellValue == "Orthopaedics") {
            cell.getRow().getElement().css({
              "background-color": "rgba(28, 124, 214,0.2)"
            });
            return cellValue;
          } else if (cellValue == "Cardiology") {
            cell.getRow().getElement().css({
              "background-color": "rgba(121, 80, 242,0.2)"
            });
            return cellValue;
          } else {
            cell.getRow().getElement().css({
              "background-color": "transparent"
            });
            return cellValue;
          }
        }
      }, {
        title: "DM",
        field: "diabetes",
        cellClick: function(e, cell) {
          var cellValue = cell.getValue();
          var row = cell.getRow();
          var name = row.getCell("name").getValue();
          if (name === undefined) {
            return false
          } else {
            if (cellValue == "true") {
              cell.setValue("false")
            } else {
              cell.setValue("true")
            }
          }
        },
        formatter: thinkGlucose,
        align: "center",
        width: 80,
      }, {
        title: "MedRec",
        field: "medrec",
        cellClick: function(e, cell) {
          var cellValue = cell.getValue();
          if (cellValue == "urgent") {
            cell.setValue("done")
          } else if (cellValue == "yes") {
            cell.setValue("done")
          } else if (cellValue == "done") {
            cell.setValue("yes")
          }
        },
        cellDblClick: function(e, cell) {
          var cellValue = cell.getValue();
          if (cellValue == "yes") {
            cell.setValue("urgent")
          } else {
            return false
          }
        },
        formatter: checkBox2,
        align: "center",
        width: 110
      },
      {
        title: "PT / OT",
        field: "ptot",
        cellClick: function(e, cell) {
          var cellValue = cell.getValue();
          var row = cell.getRow();
          var name = row.getCell("name").getValue();
          if (name === undefined) {
            return false
          } else {
            if (cellValue === undefined) {
              cell.setValue("yes")
            } else if (cellValue == "yes") {
              cell.setValue("done")
            } else if (cellValue == "done") {
              cell.setValue(undefined)
            }
          }
        },
        formatter: checkBox,
        align: "center",
        width: 110
      }, {
        title: "Outcome",
        field: "outcome",
        align: "center",
        editor: outcomeEditor,
        editable: editCheck,
        formatter: outcomeFormatter,
        width: 160
      }, {
        title: "Allocated",
        field: "allocated",
        editor: allocatedEditor,
        align: "center",
        width: 160,
        editable: editCheck,
        headerSort: false,
      }, {
        title: "Notes / Plan",
        field: "notes",
        editor: true,
        editable: editCheck,
        headerSort: false,
      }, {
        title: "Move",
        width: 70,
        formatter: moveIcon,
        align: "center",
        headerSort: false,
        cellClick: function(e, cell) {
          var row = cell.getRow()
          var bed = row.getIndex();
          var name = row.getCell("name").getValue();
          var moveModal = $('#moveModal');
          if (name === undefined) {
            return false
          } else {
            var noName = $('[tabulator-field="name"]:empty');
            var noNameBed = noName.siblings('[tabulator-field="bed"]')
            var bedList = noNameBed.map(function() {
              return $(this).text();
            }).get().join(',');
            var bedSelect = $('#bedSelect');
            bedSelect.empty();
            $('#moveBed').text(bed);
            $('#moveName').text(name);
            $.each(bedList.split(','), function(i, e) {
              bedSelect.append($('<option></option>', {
                value: e,
                text: e
              }));
            });
            moveModal.modal('show');
            $('#moveButton').off().on('click', function(e) {
              var startRow = cell.getRow();
              var startBed = row.getIndex();
              var newBed = bedSelect.val()
              var newRow = $('#amu-whiteboard').tabulator("getRow", newBed);
              console.log('bed ' + startRow + ' will be updated to ' + newBed + ' and bed ' + newRow + ' will be updated to ' + startBed);
              startRow.update({
                "bed": newBed
              });
              newRow.update({
                "bed": startBed
              });
              sortByBed();
              saveData();
              moveModal.modal('hide');
            })
          }
        }
      },
      {
        title: "Admit",
        width: 70,
        formatter: admitIcon,
        align: "center",
        headerSort: false,
        cellClick: function(e, cell) {
          var row = cell.getRow()
          var bed = row.getIndex();
          var name = row.getCell("name").getValue();
          var addModal = $('#addModal');
          if (name === undefined) {
            $('#admitBed').text(bed);
            addModal.modal('show');
          } else {
            $('#addwarnBed').text(bed);
            $('#addwarnName').text(name);
            $('#addwarnModal').modal('show');
          }
        }
      }, {
        title: "Disch",
        width: 70,
        formatter: deleteIcon,
        align: "center",
        headerSort: false,
        cellClick: function(e, cell) {
          var row = cell.getRow()
          var name = row.getCell("name").getValue();
          var deleteModal = $('#deleteModal');
          var bed = row.getIndex();

          if (name === undefined) {
            return false
          } else {
            $('#dischargeName').text(name);
            $('#dischargeBed').text(bed);
            deleteModal.modal('show');
            deleteModal.on('click', '.button-cancel', function() {
              deleteModal.modal('hide');
            });
            deleteModal.on('click', '.button-warning', function() {
              row.update({
                "name": undefined,
                "time": undefined,
                "los": "",
                "specialty": "",
                "diabetes": "",
                "medrec": undefined,
                "ptot": undefined,
                "outcome": "",
                "allocated": "",
                "notes": ""
              });
              sortByBed();
              saveData();
              checkDuplicates();
              deleteModal.modal('hide');
            });
          }
        }
      }
    ],
    dataEdited: function(data) {
      localStorage.setItem("tabulator-data", JSON.stringify(data));
    },
    rowAdded: function(row) {
      $.ajax({
        url: "aec-add.php",
        data: row.getData(),
        type: "POST",
        dataType: "json",
      })
    },
    rowDeleted: function(row) {
      var id = row.getIndex();
      $.ajax({
        url: "aec-delete.php",
        data: {
          id: id
        },
        dataType: "json",
        type: "POST",
      })
    },
    cellEdited: function(cell) {
      var value = cell.getValue();
      var field = cell.getField();
      var id = cell.getRow().getIndex();
      $.ajax({
        data: 'field=' + field + '&value=' + value + '&id=' + id,
        url: "aec-update.php",
        type: "POST",
      })
    },
    ajaxError: function(xhr, textStatus, errorThrown) {
      var data = localStorage.getItem("tabulator-data");
      if (data) {
        $("#amu-whiteboard").tabulator("setData", JSON.parse(data));
      }
    },
  });

  function updateTable() {
    var data = localStorage.getItem("tabulator-data");
    if (data) {
      $("#amu-whiteboard").tabulator("setData", JSON.parse(data));
    }
    $("#amu-whiteboard").tabulator("setSort", "bed", "asc");
    statusUpdate();
    sortByBed();
    checkDuplicates();

  }


  $(window).resize(function() {
    $("#amu-whiteboard").tabulator("redraw", true);
  });
  updateTable();
  statusUpdate();
  setInterval(updateTable, 30000);
```

**Comment by olifolkerd** [comment]
Hey,

Thanks for sending that over, on closer inspection i can see where you are going wrong.

the arguments ***a*** and ***b*** are the values of the column sorted so have no property of ***elapsed*** you need to be using the ***aData*** and ***bData*** row components to get that property:

```js
var customSort = function(a, b, aData, bData) {
   return String(aData.getData().elapsed).localeCompare(String(bData.getData().elapsed));
}
```

Let me know if that helps,

Cheers

Oli

**Comment by tomheaps** [comment]
Hi Oli,

I have upgraded to Tabulator 3.3 and done as you suggested just changing aData to aRow as stipulated in the updated docs so my code is now:

```
{
        title: "Elapsed",
        field: "elapsed",
        formatter: timeElapsed,
        width: 120,
        align: "center",
        sorter: "number",
        visible: false,
      }, {
        title: "LOS",
        field: "los",
        align: "center",
        width: 120,
        formatter: cLos,
        sorter: function(a, b, aRow, bRow) {
           console.log(aRow.getData().elapsed + bRow.getData().elapsed)
          return String(aRow.getData().elapsed).localeCompare(String(bRow.getData().elapsed));
        }
      },
```

This is still not sorting the "los" column according to the values in the "elapsed" column - when I click on the header to sort nothing happens! 

When I log aRow.getData().elapsed and bRow.getData().elapsed, the console is returning "NaN" for both if this helps?

Any other suggestions gratefully received??

**Comment by olifolkerd** [comment]
that would suggest that the data is not in a format that you are expecting,

what happens with this log statement:
```js
console.log("compare", aRow.getData().elapsed, bRow.getData().elapsed)
```

**Comment by tomheaps** [comment]
When I ran `console.log("compare", aRow.getData().elapsed, bRow.getData().elapsed) `the console returned compare undefined undefined

So it looks like this is not returning the text strings contained within the cells of this column.

If I change the selectors for comparison to `aRow.getCell("elapsed").getElement().text()`, this correctly returns the strings within the cells of the "elapsed" column however this approach breaks the sorter function when I set up column def as:
```
{
        title: "LOS",
        field: "los",
        align: "center",
        width: 120,
        formatter: cLos,
        sorter: function(a, b, aRow, bRow) {
          console.log(aRow.getCell("elapsed").getElement().text());
          return String(aRow.getCell("elapsed").getElement().text()).localeCompare(String(aRow.getCell("elapsed").getElement().text()));
         
        }
      }
```
 And I get the following error message:
```
Uncaught TypeError: Cannot read property 'getComponent' of undefined
    at r.getCell (http://swft-3-0-tomheaps44150.codeanyapp.com/js/tabulator.min.js:3:4784)
    at B.sorter (http://swft-3-0-tomheaps44150.codeanyapp.com/js/amu.js:430:28)
    at B._sortRow (http://swft-3-0-tomheaps44150.codeanyapp.com/js/tabulator.min.js:6:19126)
    at http://swft-3-0-tomheaps44150.codeanyapp.com/js/tabulator.min.js:6:18806
    at Array.sort (native)
    at B._sortItem (http://swft-3-0-tomheaps44150.codeanyapp.com/js/tabulator.min.js:6:18779)
    at http://swft-3-0-tomheaps44150.codeanyapp.com/js/tabulator.min.js:6:18227
    at Array.forEach (<anonymous>)
    at B.sort (http://swft-3-0-tomheaps44150.codeanyapp.com/js/tabulator.min.js:6:18076)
    at a.refreshActiveData (http://swft-3-0-tomheaps44150.codeanyapp.com/js/tabulator.min.js:2:28024)
```

Any other thoughts?

**Comment by olifolkerd** [comment]
You definitely dont want to be getting the text from the DOM element,  that isnt safe.

Can you check what values you are getting on the ***getData()*** function:
```js
console.log("compare", aRow.getData(), bRow.getData())
```
This should be an object containing all data from the row being sorted
if this causes an error, try:
```js
console.log("compare", aRow, bRow)
```
and let me know what you get.

Cheers

Oli

**Comment by tomheaps** [comment]
I have tried what you suggested and am getting strange results.

Objects are being returned containing data for the rows (see below) but the values for certain fields (including the field I am trying to sort and the field I am sorting by) are returning as "undefined" even though there are strings in these fields in the table (and in the html of the table).

```
data
:
allocated
:
undefined
bed
:
"A2"
diabetes
:
"true"
elapsed
:
undefined
los
:
undefined
medrec
:
"yes"
name
:
"GDSGSDGD, Gdsgdsg"
notes
:
undefined
ot
:
undefined
outcome
:
undefined
pt
:
undefined
specialty
:
undefined
time
:
"17 10 02 21 12"

```
I suspect that the problem is that I am using custom formatters to display data in these fields using data from the "time" column (see the customFormatters in my long post above) rather than actually inserting values into these columns manually?

Not sure if there is any fix for this?

**Comment by olifolkerd** [comment]
Ahh yes,

Using formatters in that way is exactly what is causing your problem, you want to be using ***mutators*** if you want the data to be stored in the table and accessible to sorters, formatters are for display only, they do not affect the actual data.
```js
  var timeElapsedMutator = function(value, data, type, mutatorParams) {
    var timeCol = data.time;
    var startTime = moment(timeCol, "YY MM DD HH mm");
    var currentTime = moment();
    var elapsedTime = currentTime.diff(startTime, 'minutes');
    if (timeCol === undefined) {
      return undefined
    } else {
      return elapsedTime
    }
  }
```

Then in your column definition:
```js
{
        title: "Elapsed",
        field: "elapsed",
        mutator: timeElapsedMutator,
        width: 120,
        align: "center",
        visible: false,
},
```

Checkout the [Mutator Documentation](http://tabulator.info/docs/3.3#get-set) for more info.

Let me know if that helps.

Cheers

Oli :)

**Comment by tomheaps** [comment]
Finally, I have got it working by substituting the custom formatters with custom mutators and by using the custom sort function:

` sorter: function(a, b, aRow, bRow, sorterParams) {
          return (aRow.getData().elapsed) - (bRow.getData().elapsed);
        }`

Thank you so much for all your help and patience!
