### ISSUE TITLE
row.Select bug in 3.3

### ISSUE THREAD

**Issue by mikeshow** [olifolkerd/tabulator#624]
Hi Oli,

I have this code:
```javascript
         rowFormatter: function (row) {
            var data = row.getData();
            if (data.tariff_id !== 0)
            {
               // It's a tariff, select the line by default.
               row.select();
            }
         },
```
In 3.2 it works. In 3.3 it doesn't.

Here the devtools:

```
VM312:426 response.data.content
VM312:427 (25) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
0:
 capacite: "95"
 id: "27"
 prod_note: "<p>3 salles jusqu&#39;&agrave; 30 pax th&eacute;&acirc;tre</p>↵"
 prod_title: "3.14 Hotel"
 provider_id: "29"
 provider_name: "3.14 Hotel"
 tarif_title: ""
 tariff_id: 0
 undefined: undefined
 ville_name: "Cannes Mandelieu Le Cannet"
 __proto__: Object
 1: {id: "27", provider_name: "", prod_title: "", prod_note: "", capacite: 0, …}
 2: {id: "27", provider_name: "", prod_title: "", prod_note: "", capacite: 0, …}
 3: {id: "27", provider_name: "", prod_title: "", prod_note: "", capacite: 0, …}
 4: {id: "75", provider_name: "AC Hotel Ambassadeur", prod_title: "AC Hotel Ambassadeur", prod_note: "<p>19 salles jusqu&#39;&agrave; 200 pax th&eacute;&acirc;tre</p>↵", capacite: "221", …}
 5: {id: "75", provider_name: "", prod_title: "", prod_note: "", capacite: 0, …}
 6: {id: "75", provider_name: "", prod_title: "", prod_note: "", capacite: 0, …}
 ...
VM312:428 dp_list
VM312:429 (25) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
  0: {id: "27", provider_name: "3.14 Hotel", prod_title: "3.14 Hotel", prod_note: "<p>3 salles jusqu&#39;&agrave; 30 pax th&eacute;&acirc;tre</p>↵", capacite: "95", …}
  1:
   capacite: 0
   id: "27"
   prod_note: ""
   prod_title: ""
   provider_id: 0
   provider_name: ""
   tarif_title: "Single Room"
   tariff_id: "14"
   undefined: undefined
   ville_name: ""
   __proto__: Object
2: {id: "27", provider_name: "", prod_title: "", prod_note: "", capacite: 0, …}
3: {id: "27", provider_name: "", prod_title: "", prod_note: "", capacite: 0, …}
4: {id: "75", provider_name: "AC Hotel Ambassadeur", prod_title: "AC Hotel Ambassadeur", prod_note: "<p>19 salles jusqu&#39;&agrave; 200 pax th&eacute;&acirc;tre</p>↵", capacite: "221", …}
5: {id: "75", provider_name: "", prod_title: "", prod_note: "", capacite: 0, …}
6: {id: "75", provider_name: "", prod_title: "", prod_note: "", capacite: 0, …}
...
tabulator.min.js:3 Uncaught TypeError: Cannot read property 'Row' of undefined
    at r.select (http://localhost/wp_dmcjsquote/wp-content/plugins/mcdmcquote/includes/tabulator/tabulator.min.js:3:5213)
    at Object.rowFormatter (<anonymous>:1743:20)
    at l.initialize (http://localhost/wp_dmcjsquote/wp-content/plugins/mcdmcquote/includes/tabulator/tabulator.min.js:3:7516)
    at http://localhost/wp_dmcjsquote/wp-content/plugins/mcdmcquote/includes/tabulator/tabulator.min.js:2:29753
    at Array.forEach (<anonymous>)
    at a._simpleRender (http://localhost/wp_dmcjsquote/wp-content/plugins/mcdmcquote/includes/tabulator/tabulator.min.js:2:29688)
    at a.renderTable (http://localhost/wp_dmcjsquote/wp-content/plugins/mcdmcquote/includes/tabulator/tabulator.min.js:2:29164)
    at a.refreshActiveData (http://localhost/wp_dmcjsquote/wp-content/plugins/mcdmcquote/includes/tabulator/tabulator.min.js:2:28575)
    at a.setData (http://localhost/wp_dmcjsquote/wp-content/plugins/mcdmcquote/includes/tabulator/tabulator.min.js:2:22756)
    at t.(anonymous function).(anonymous function).setData (http://localhost/wp_dmcjsquote/wp-content/plugins/mcdmcquote/includes/tabulator/tabulator.min.js:3:23462)
r.select @ tabulator.min.js:3
rowFormatter @ VM282:1743
l.initialize @ tabulator.min.js:3
(anonymous) @ tabulator.min.js:2
a._simpleRender @ tabulator.min.js:2
a.renderTable @ tabulator.min.js:2
a.refreshActiveData @ tabulator.min.js:2
a.setData @ tabulator.min.js:2
setData @ tabulator.min.js:3
(anonymous) @ jquery-ui.min.js:6
(anonymous) @ jquery-ui.min.js:6
each @ jquery-3.2.1.min.js:2
each @ jquery-3.2.1.min.js:2
t.fn.(anonymous function) @ jquery-ui.min.js:6
success @ VM312:466
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
A @ jquery-3.2.1.min.js:4
(anonymous) @ jquery-3.2.1.min.js:4
XMLHttpRequest.send (async)
send @ jquery-3.2.1.min.js:4
ajax @ jquery-3.2.1.min.js:4
refresh_display_tabulator_prodtariffs @ VM312:403
show_the_select_prodtariff_table @ VM312:369
(anonymous) @ VM312:509
p @ jquery-3.2.1.min.js:2
globalEval @ jquery-3.2.1.min.js:2
text script @ jquery-3.2.1.min.js:4
Qb @ jquery-3.2.1.min.js:4
A @ jquery-3.2.1.min.js:4
(anonymous) @ jquery-3.2.1.min.js:4
XMLHttpRequest.send (async)
send @ jquery-3.2.1.min.js:4
ajax @ jquery-3.2.1.min.js:4
select_the_product_tariff @ VM282:2393
(anonymous) @ VM282:2031
r @ jquery.transit.min.js:1
setTimeout (async)
v @ jquery.transit.min.js:1
z @ jquery.transit.min.js:1
dequeue @ jquery-3.2.1.min.js:3
(anonymous) @ jquery-3.2.1.min.js:3
each @ jquery-3.2.1.min.js:2
each @ jquery-3.2.1.min.js:2
queue @ jquery-3.2.1.min.js:3
c @ jquery.transit.min.js:1
t.fn.transition.t.fn.transit @ jquery.transit.min.js:1
(anonymous) @ VM282:2026
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3

```

As you can see there is an 'undefined' element in the array. I don't know why it is added by wp_send_json_success() but so far everything worked well.

**Comment by olifolkerd** [comment]
Hey @mikeshow,

There was a regression in the 3.3 release on row select functionality, I pushed a fix to the master branch a couple of days ago and will being releasing a patch release with a fix for it later today.

Thanks for the heads up!

Cheers

Oli :)

**Comment by mikeshow** [comment]
Thanks Oli.
