### ISSUE TITLE
Persistent layout, error 'extEcists'

### ISSUE THREAD

**Issue by a-naslund** [olifolkerd/tabulator#732]
Hi,

Using Tabulator 3.2 I get an error in the console when **persistentLayout** is enabled if I'm using a variable to hold the column definition instead of having the definition directly within the constructor element, all other features are however working fine when using the variable.

**Causes Error**
var mycols = [{title:"column1", ..... }];
$("#example-table").tabulator({ columns: mycols, ....});

Uncaught TypeError: Cannot read property 'extExists' of undefined
    at e.a.hide (xxx/tabulator.min.js:1:18021)
    at e.a._buildColumnHeader (xxx/tabulator.min.js:1:13700)
    at e.a._buildHeader (xxx/tabulator.min.js:1:10721)
    at new e (xxx/tabulator.min.js:1:9933)
    at n._addColumn (xxx/tabulator.min.js:1:2513)
    at xxx/tabulator.min.js:1:2293
    at Array.forEach (<anonymous>)
    at n.setColumns (xxx/tabulator.min.js:1:2269)
    at t.(anonymous function).(anonymous function)._buildElement (xxx/tabulator.min.js:2:20106)
    at t.(anonymous function).(anonymous function)._buildElement (xxx/jquery-ui.min.js:6:4499)

**Works**
$("#example-table").tabulator({ columns: [{title:"column1", ....}] ....});

.... is just replacement for the rest of the configuration parameters.
and I've removed the server url from the error message.

**Comment by olifolkerd** [comment]
Hey @a-naslund 

Can you try upgrading to version 3.3.1 and let me know if you still get the error.

Cheers

Oli

**Comment by a-naslund** [comment]
3.3.1 resolved the initial problem but I will need to submit a new one instead. /Thanks
